### ISSUE TITLE
supporting auto indexing

### ISSUE THREAD

**Issue by nikueater** [nikueater/siteelm#1]
## overview

supporting the auto indexing, which is useful for making blogs or news sites.

## idea

Like the "external" property in preambles, we provides the "preamblesIn" property which generate a list of contents in a directory. 

```yaml
---
module: Layout.Index
contents: 
    preamblesIn: ./articles
---
```
